[package]
name = "privacy-preserving-authentication"
version = "0.1.0"
authors = ["akakou <akama@keio.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = "0.5.10"
rand = "0.7.3"